In [1]:
import numpy as np 

In [2]:
# column vector
c = np.array([1, 2, 3])
print(c.shape)


# obtaining a particular entry
print(c[0])

(3,)
1


In [8]:
# row vector 
r = np.array([ [1, 2, 3] ])
print(r.shape)

# obtaining a particular entry
print(r[0, 1])

(1, 3)
2


In [15]:
# create a matrix with all zeros
a = np.zeros( (2 , 2) )
print(a)

# create a matrix with all ones
b = np.ones( (2, 2) )
print(b)

# create a matrix filled with the same constant
c = np.full( (2, 2) , 7)
print(c)

# create a matrix with random value
d = np.random.random( (2, 2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.19872837 0.20646936]
 [0.04860209 0.91043063]]


In [17]:
# create a matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
# creating another matrix
B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(B)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
# transpose matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
# matrix-matrix multiplication
np.dot(A, B)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [23]:
# matrix-matrix multiplication
# size should match ! 

np.dot(B, A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [33]:
# coefficient    matrix A and a vector B
A = np.array([
    [60, 5.5, 1],
    [65, 5.0, 0],
    [55, 6.0, 1]
])

B = np.array(
    [66, 70, 78] 
)



In [34]:
# identity matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# computing a inverse
from numpy.linalg import inv 
A_inv = inv(A)
print(A_inv)

[[ 0.08695652  0.00869565 -0.08695652]
 [-1.13043478  0.08695652  1.13043478]
 [ 2.         -1.         -1.        ]]


In [36]:
np.dot(A, A_inv)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [37]:
# wrong matrix multiplication / this is element-wise of matrix multiplication
A * A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [38]:
# correct matrix multiplication
A.dot(A_inv)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [39]:
# solution of a linear system
x = A_inv.dot(B)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [41]:
# a better way to solve the same linear system
# inverse 값 자체를 구하는 경우는 거의 없다. 
from numpy.linalg import solve
x = solve(A, B)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [42]:
a = np.array([
    [1, 2],
    [3, 4]
])
print(a)

[[1 2]
 [3 4]]
