In [1]:
import numpy as np

np를 사용하는 이유는 list와의 속도차이

In [6]:
my_arr = np.array(1000000)
%time for _ in range(10) : my_arr2 = my_arr*2

Wall time: 0 ns


In [7]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.19 s


In [8]:
arr_1d = np.array([1, 2, 3, 4])
arr_1d

array([1, 2, 3, 4])

In [9]:
arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
    ])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr_3d = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]],
    [[2, 2, 2],
    [3, 3, 3],
    [4, 4, 4]]
])
print(arr_3d.shape)
print(arr_3d.ndim)

(2, 3, 3)
3


In [16]:
print("arr_2d ndim:", arr_2d.ndim)
print("arr_2d shape:", arr_2d.shape)
print("arr_2d size:", arr_2d.size)

arr_2d ndim: 2
arr_2d shape: (2, 4)
arr_2d size: 8


In [17]:
print("dtype:", arr_2d.dtype)

dtype: int32


In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((2, 3, 6), dtype = "int64")

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]], dtype=int64)

In [22]:
np.ones((3, 6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

- ndarray 생성하기

In [26]:
samples = np.random.normal(size = (4, 4))
samples

array([[ 1.53066386, -0.51463869,  0.62315323, -0.06465449],
       [ 1.11157316, -0.70289662,  0.32552629,  0.05720535],
       [ 0.50483523, -1.07761862,  0.67495987,  1.18802293],
       [ 0.15878368, -0.81481543, -1.93058743, -1.40627758]])

In [27]:
arr = np.random.randint(20, size = (2, 3))
arr

array([[ 5, 17, 14],
       [11, 19,  0]])

In [28]:
arr * arr

array([[ 25, 289, 196],
       [121, 361,   0]])

In [29]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
1 / arr

<ipython-input-30-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([[0.2       , 0.05882353, 0.07142857],
       [0.09090909, 0.05263158,        inf]])

In [31]:
arr * 0.5

array([[2.5, 8.5, 7. ],
       [5.5, 9.5, 0. ]])

In [36]:
arr1 = np.random.randint(20, size = (2, 3))
arr1

array([[ 0, 10, 16],
       [18, 18,  2]])

In [37]:
arr2 = np.random.randint(20, size = (2, 3))

In [38]:
arr2 > arr1

array([[ True,  True,  True],
       [False, False,  True]])

In [40]:
np.random.seed(0)

In [42]:
x1 = np.random.randint(10, size = 6)
x1

array([3, 5, 2, 4, 7, 6])

In [43]:
x1[0]

3

In [44]:
x1[5]

6

In [45]:
x1[-1]

6

In [46]:
x2 = np.random.randint(10, size = (3, 4))
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [47]:
x2[0, 0]

8

In [48]:
x2[2, -1]

9

In [49]:
x2[0, 0] = 12
x2

array([[12,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [56]:
x1 = np.array([[
    [1, 2, 3],
    [2, 3, 4],
    [5, 6, 7]],
    [[1, 2, 2],
    [3, 3, 3],
    [3, 5, 6]]
])
print(x1.ndim)
print(x1[0, 0, 0])

3
1


In [59]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x[5:]

array([5, 6, 7, 8, 9])

In [61]:
x[4:7]

array([4, 5, 6])

In [62]:
x[::2]

array([0, 2, 4, 6, 8])

In [63]:
x[5::-2]

array([5, 3, 1])

In [66]:
x_2d = np.array([np.arange(5), np.arange(5)])
print(x_2d[0,:])
print(x_2d[0,::-1])

[0 1 2 3 4]
[4 3 2 1 0]


In [67]:
names = np.array(['Bob', 'Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [99]:
data = np.random.randn(7, 4)
data

array([[-1.27814912,  1.43737068, -0.07770457,  1.08963016],
       [ 0.09654267,  1.41866711,  1.16827314,  0.94718595],
       [ 1.08548703,  2.38222445, -0.40602374,  0.26644534],
       [-1.35571372, -0.11410253, -0.84423086,  0.70564081],
       [-0.39878617, -0.82719653, -0.4157447 , -0.52451219],
       [ 0.81310127, -0.22925063,  2.16171737, -0.95693143],
       [ 0.06731083,  0.20649884, -0.45688133, -1.05997576]])

In [100]:
names == 'Bob'


array([ True, False, False,  True, False, False, False])

In [101]:
data[names == 'Bob']

array([[-1.27814912,  1.43737068, -0.07770457,  1.08963016],
       [-1.35571372, -0.11410253, -0.84423086,  0.70564081]])

In [102]:
data[names == 'Bob', 2:]

array([[-0.07770457,  1.08963016],
       [-0.84423086,  0.70564081]])

In [103]:
data[names == 'Bob', 3]

array([1.08963016, 0.70564081])

In [104]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [105]:
data[names != 'Bob']

array([[ 0.09654267,  1.41866711,  1.16827314,  0.94718595],
       [ 1.08548703,  2.38222445, -0.40602374,  0.26644534],
       [-0.39878617, -0.82719653, -0.4157447 , -0.52451219],
       [ 0.81310127, -0.22925063,  2.16171737, -0.95693143],
       [ 0.06731083,  0.20649884, -0.45688133, -1.05997576]])

In [106]:
data[~(names == 'Bob')]

array([[ 0.09654267,  1.41866711,  1.16827314,  0.94718595],
       [ 1.08548703,  2.38222445, -0.40602374,  0.26644534],
       [-0.39878617, -0.82719653, -0.4157447 , -0.52451219],
       [ 0.81310127, -0.22925063,  2.16171737, -0.95693143],
       [ 0.06731083,  0.20649884, -0.45688133, -1.05997576]])

In [107]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [108]:
data[mask]

array([[-1.27814912,  1.43737068, -0.07770457,  1.08963016],
       [ 1.08548703,  2.38222445, -0.40602374,  0.26644534],
       [-1.35571372, -0.11410253, -0.84423086,  0.70564081],
       [-0.39878617, -0.82719653, -0.4157447 , -0.52451219]])

In [110]:
data < 0 

array([[ True, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [111]:
data[data < 0] = 0
data

array([[0.        , 1.43737068, 0.        , 1.08963016],
       [0.09654267, 1.41866711, 1.16827314, 0.94718595],
       [1.08548703, 2.38222445, 0.        , 0.26644534],
       [0.        , 0.        , 0.        , 0.70564081],
       [0.        , 0.        , 0.        , 0.        ],
       [0.81310127, 0.        , 2.16171737, 0.        ],
       [0.06731083, 0.20649884, 0.        , 0.        ]])

In [112]:
arr = np.random.randint(100, size = (8, 4))
arr

array([[ 0, 14, 99, 53],
       [12, 42, 84, 75],
       [68,  6, 68, 47],
       [ 3, 76, 52, 78],
       [15, 20, 99, 58],
       [23, 79, 13, 85],
       [48, 49, 69, 41],
       [35, 64, 95, 69]])

In [116]:
arr[[4, 3, 0, 6]]

array([[15, 20, 99, 58],
       [ 3, 76, 52, 78],
       [ 0, 14, 99, 53],
       [48, 49, 69, 41]])

In [117]:
arr[[-3, -5, -7]]

array([[23, 79, 13, 85],
       [ 3, 76, 52, 78],
       [12, 42, 84, 75]])

In [118]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([12, 85, 64, 68])

In [120]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[12, 75, 42, 84],
       [23, 85, 79, 13],
       [35, 69, 64, 95],
       [68, 47,  6, 68]])

In [121]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [123]:
x2

array([[12,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [126]:
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
x2_sub

array([[99,  8],
       [ 7,  7]])

In [127]:
x2 

array([[99,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [128]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy 


array([[99,  8],
       [ 7,  7]])

In [129]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  8],
       [ 7,  7]])

In [130]:
x2

array([[99,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [131]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [132]:
x.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
x.reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [162]:
x = np.random.randint(6, size = (2, 3))
y = np.random.randint(6, size = (2, 3))

In [139]:
np.concatenate([x, y])

array([[0, 1, 2],
       [4, 2, 0],
       [5, 3, 2],
       [2, 5, 0]])

In [140]:
np.concatenate([x, y], axis = 1)

array([[0, 1, 2, 5, 3, 2],
       [4, 2, 0, 2, 5, 0]])

In [143]:
x = [0, 1, 1, 0, 1, 0]


In [144]:
arr_x = np.array(x)
arr_x

array([0, 1, 1, 0, 1, 0])

In [160]:
arr_x.reshape(-1,1)

array([[0],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [163]:
np.vstack([x, y])

array([[5, 1, 0],
       [2, 2, 3],
       [2, 3, 2],
       [1, 2, 3]])

In [164]:
np.hstack([x, y])

array([[5, 1, 0, 2, 3, 2],
       [2, 2, 3, 1, 2, 3]])

In [165]:
z = np.random.randint(16, size = (4, 4))
z

array([[14, 11,  3,  2],
       [14,  3,  4,  1],
       [ 2, 11, 14,  9],
       [10,  1,  4, 10]])

In [166]:
upper, lower = np.vsplit(z, [2]) # 짤라낼 범위 [2]
left, right = np.hsplit(z, [2])

In [168]:
print(upper)

print(lower)

[[14 11  3  2]
 [14  3  4  1]]
[[ 2 11 14  9]
 [10  1  4 10]]


In [169]:
print(left)

print(right)

[[14 11]
 [14  3]
 [ 2 11]
 [10  1]]
[[ 3  2]
 [ 4  1]
 [14  9]
 [ 4 10]]


In [175]:
np.split(z, 2, axis = 1)

[array([[14, 11],
        [14,  3],
        [ 2, 11],
        [10,  1]]),
 array([[ 3,  2],
        [ 4,  1],
        [14,  9],
        [ 4, 10]])]