In [1]:
# numpy 
# Numpy(Numerical Python) is a Python library used to work with numerical data.
# Numpy includes functions and structures that can perform a wide variety of mathematical operations.
# To start using NumPy, we fires need to import it;
import numpy as np 

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[1][2])

6


In [6]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# ndim returns the number of dimensions of the array/
print(x.ndim)

# size return the total number of elements of the array.
print(x.size)

# shape returns a tuple of integers that indicate the number of elements stored along each dimension of the array.
print(x.shape)

2
9
(3, 3)


In [9]:
x = np.array([2, 1, 3])
print(x)

# add an element
x = np.append(x, 4)
print(x)

# delete at index
x = np.delete(x, 0)
print(x)

# sort the array
x = np.sort(x)
print(x)

[2 1 3]
[2 1 3 4]
[1 3 4]
[1 3 4]


In [11]:
# np.arange() allows you to create an array that contains a range of evenly spaced intervals (similar to a Python range);
np.arange(2, 10, 3)

array([2, 5, 8])

In [12]:
# What is the output of this code?

x = np.arange(2, 8, 2)
x = np.append(x, x.size)
x = np.sort(x)
print(x[1])

3


In [13]:
# Reshape
# Recall that shape refers to the number of rows and columns in the array.
# For example, let's consider the following array;
# we can change our 1-dim array to an array with 3 rows and 2 columns;
x = np.arange(1, 7)
z = x.reshape(3, 2)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# Reshape can also do the opposite: take a 2-dim array and make a 1-dim array from it;
x = np.array([[1, 2], [3, 4], [5, 6]])
z = x.reshape(6) # x.flatten()
z

array([1, 2, 3, 4, 5, 6])

In [17]:
# Indexing and Slicing
# NumPy arrays can be indexed and sliced the same way that Python lists are.
x = np.arange(1, 10)
print(x[0:2])
print(x[5:])
print(x[:2])
print(x[-3:])

[1 2]
[6 7 8 9]
[1 2]
[7 8 9]


In [18]:
# Conditions
# You can provide a condition as the index to select the elements that fulfill the given condition.
x = np.arange(1, 10)
print(x[x<4])

[1 2 3]


In [19]:
print(x[(x>5) & (x%2==0)])

[6 8]


In [20]:
# Operations
# It is easy to perform basic mathematical operations with arrays.
# For example, to find the sum of all elements, we use the sum() function;

x = np.arange(1, 10)
print(x.sum())

45


In [ ]:
# Similarly, min() and max() can be used to get the smallest and largest elements.
# We can also perform operations between the array and a single number.
# For example, we can multiply all elements by 2:
x = np.arange(1, 10)
y = x*2

In [21]:
# Remember the summary statistics we learned in the previous module? Those included mean, median, variance and standard deviation.
# NumPy arrays have built-in functions to return those values.
x = np.array([14, 18, 19, 24, 26, 33, 42, 55, 67])
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

33.111111111111114
26.0
292.5432098765432
17.10389458212787


In [ ]:
# What is the output?
x = np.arange(3, 9)
z = x.reshape(2, 3)
print(z[1][1])


In [22]:
# House Prices
# You are given an array that represents house prices.
# Calculate and output the percentage of houses that are within one standard deviation from the mean.
# multiplicate 100
data = np.array([
    150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 
    280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000]
    )


In [31]:
# sol

mean = np.mean(data)
std = np.std(data)

answer = data[(data < (mean+std)) & (data > (mean-std))]
print(len(answer) / len(data) * 100)

0.625


390366.199846448