In [1]:
import pandas as pd 
import numpy as np 

In [5]:

input1 = np.array([
    [1, 0, 0, 0, 0, 0, 0]
])


input2 = np.array([
    [0, 0, 1, 0, 0, 0, 0]
])

In [6]:
w_input = np.random.randn(7, 3) # setting random weight  ( hyperparameter )

In [10]:
# h_1, h_2 는 단어의 임베딩 값이라고 보면된다. 

h_1 = np.matmul(input1, w_input) # value of hidden layer 
h_2 = np.matmul(input2, w_input) # np.matmul == np.dot 

h = ( h_1 + h_2 ) / 2

In [11]:
print( h )

[[0.82161687 0.24429476 0.19680842]]


In [12]:
w_output = np.random.randn(3, 7)
score = np.matmul(h, w_output)
print(np.round(score, 4))

[[ 0.976   1.3657  0.2943  0.785   1.1365 -0.4577 -0.0169]]


In [13]:
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    return y 
pred = softmax(score)
print(np.round(pred, 4))

[[0.1788 0.2641 0.0905 0.1477 0.21   0.0426 0.0663]]


In [18]:
pred.argmax()

1

In [21]:
# find loss function 
def cross_entropy(y, t):
    """
    y : prediction
    t : target
    """
    delta = 1e-7
    return -np.sum(t * np.log(y + delta )) / y.shape[0]

cross_entropy(pred, [0, 1, 0, 0, 0, 0, 0])

1.3314970801088066

In [22]:
# backpropagation 
ans = [0, 1, 0, 0, 0, 0, 0]
ds = np.round(pred - ans, 4)
print(ds)

[[ 0.1788 -0.7359  0.0905  0.1477  0.21    0.0426  0.0663]]


In [23]:
# calculation delta for w_output
dw_output = np.outer(h, ds)
print(np.round(dw_output, 4))

[[ 0.1469 -0.6046  0.0744  0.1214  0.1725  0.035   0.0545]
 [ 0.0437 -0.1798  0.0221  0.0361  0.0513  0.0104  0.0162]
 [ 0.0352 -0.1448  0.0178  0.0291  0.0413  0.0084  0.013 ]]


In [24]:
da = np.dot(ds, w_output.T)
print(np.round(da, 4))

[[-0.3525 -1.6069  1.0787]]


In [27]:
dw_1 = np.round(np.outer(np.array([[1, 0, 0, 0, 0, 0, 0]]), (da/2)), 4)
print(dw_1)

[[-0.1763 -0.8034  0.5393]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]]


In [28]:
dw_2 = np.round(np.outer(np.array([[0, 0, 1, 0, 0, 0, 0]]), (da/2)), 4)
print(dw_2)

[[-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.1763 -0.8034  0.5393]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]
 [-0.     -0.      0.    ]]


In [29]:
learning_rate = 1
w_input_new = w_input - learning_rate * dw_1 
w_input_new = w_input_new - learning_rate * dw_2 
print(np.round(w_input_new, 4)) # adjust weight

[[-0.2844  1.0826 -0.2635]
 [ 0.14    0.3663  0.9033]
 [ 2.2802  1.0128 -0.4215]
 [ 1.0677  1.0181 -0.6038]
 [ 1.105  -1.6156 -1.2398]
 [-2.1194  0.5039  0.127 ]
 [ 0.7149 -1.0573  0.0853]]


In [30]:
print(np.round(w_input, 4)) # origin weight

[[-0.4607  0.2792  0.2758]
 [ 0.14    0.3663  0.9033]
 [ 2.1039  0.2094  0.1178]
 [ 1.0677  1.0181 -0.6038]
 [ 1.105  -1.6156 -1.2398]
 [-2.1194  0.5039  0.127 ]
 [ 0.7149 -1.0573  0.0853]]
