In [1]:
import numpy as np 

In [2]:
input = np.array([[0, 1, 0, 0, 0, 0, 0]])

output1 = np.array([[1, 0, 0, 0, 0, 0, 0]])
output2 = np.array([[0, 0, 1, 0, 0, 0, 0]])


In [3]:
w_input = np.random.randn(7, 3)
h = np.matmul(input, w_input)

In [4]:
print(h) # value of hidden layer

[[0.12217734 0.5332095  0.81489867]]


In [5]:
w_output = np.random.randn(3, 7)
score = np.matmul(h, w_output)
print( np.round(score, 4) )

[[-0.8468  0.9658 -0.8381 -1.2009  0.401  -0.0254 -0.4979]]


In [6]:
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    return y 

def cross_entropy(y, t):
    """
    y : prediction
    t : target
    """
    delta = 1e-7
    return -np.sum(t * np.log(y + delta )) / y.shape[0]

In [7]:
pred = softmax(score)
print(np.round(pred, 4))

[[0.0625 0.3826 0.063  0.0438 0.2175 0.142  0.0885]]


In [10]:
# backpropagation 
ds1 = np.round(pred - output1, 4)
ds2 = np.round(pred - output2, 4)
ds = ds1 + ds2 
print(ds)

[[-0.875   0.7652 -0.874   0.0876  0.435   0.284   0.177 ]]


In [11]:
da = np.dot(ds, w_output.T)
print(np.round(da, 4))


[[1.1303 2.6296 0.7928]]


In [12]:
dw_input = np.outer(np.array([[0, 1, 0, 0, 0, 0, 0]]), da)
print(np.round(dw_input, 4))

[[0.     0.     0.    ]
 [1.1303 2.6296 0.7928]
 [0.     0.     0.    ]
 [0.     0.     0.    ]
 [0.     0.     0.    ]
 [0.     0.     0.    ]
 [0.     0.     0.    ]]


In [14]:
learning_rate = 1 
w_input_new = w_input - learning_rate * dw_input 
print(np.round(w_input_new, 4))

[[ 1.0013  0.2433 -0.5551]
 [-1.0081 -2.0964  0.022 ]
 [ 0.7064  0.3355 -0.6917]
 [-0.4521  1.5181  0.1448]
 [-0.9517 -0.8468 -0.4522]
 [ 0.7172 -0.9039  0.9499]
 [ 1.191   1.5772 -0.12  ]]


In [16]:
print(np.round(w_output, 4))

[[-0.4248 -0.347  -0.6018 -1.1278  1.6537 -0.295  -0.2185]
 [-0.768   1.4394 -0.0234 -0.6345  2.0652 -0.3388  0.5037]
 [-0.4729  0.2954 -0.9229 -0.8895 -1.1072  0.2348 -0.9079]]
