In [ ]:
import numpy as np 

In [2]:
# 1번
# array([[[0., 0., 0., 0.],
#         [2., 0., 0., 0.],
#         [0., 0., 0., 1.]],
#        [[0., 0., 0., 0.],
#         [0., 0., 0., 0.],
#         [2., 0., 0., 1.]]])

# 3차원출력


In [27]:
a = np.arange(1,25).reshape(2, 3, -1)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
# 2번
# result = np.where(cond, xarr, yarr)
# result 

#3번
# 1~5점까지 점수를 배열 100개 생성
# 3점 이상이면 1 
# 3점 이하면 0

In [28]:
a = np.zeros((8,8))
a = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 1)
np.where(a == 1, a, 10)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1., 10., 10., 10., 10., 10., 10., 10., 10.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [26]:
a = np.random.randint(1, 5, 100)
np.where(a >= 3, 1, 0)

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0])