In [1]:
import numpy as np 

In [4]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.ones((1, 2))

array([[1., 1.]])

In [7]:
np.full((2, 2), 7, 'int64') # 2 by 2 matrix 를 7로 가득채운다

array([[7, 7],
       [7, 7]], dtype=int64)

In [8]:
np.eye(2) #identity matrix

array([[1., 0.],
       [0., 1.]])

In [9]:
np.empty([3, 2]) # 3 by 2 matrix를 0을 할당한 공백의 matrix로 채운다. 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.random.random((2, 2)) # 0~1 사이 값으로 2 by 2 matrix 

array([[0.164568  , 0.86197269],
       [0.12376013, 0.7965844 ]])

In [17]:
np.random.randint(45, size = 6)

array([ 2, 12, 19, 16,  6, 44])

In [18]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
# fancy index
a = np.array([[1, 2], [3, 4], [5, 6]])
np.array([a[0, 0], a[1, 1], a[2, 0]])

array([1, 4, 5])

In [23]:
a[[0, 1, 2], [0, 1, 0]] # same result

array([1, 4, 5])

In [24]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64) 

In [25]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [32]:
np.add( x , y )

array([[ 6.,  8.],
       [10., 12.]])

In [31]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [33]:
np.multiply(x, y) # element-wise

array([[ 5., 12.],
       [21., 32.]])

In [34]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [35]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [36]:
from scipy.linalg import sqrtm
sqrtm(x) # 제곱근을 찾는다. 

array([[0.55368857+0.46439416j, 0.80696073-0.21242648j],
       [1.21044109-0.31863972j, 1.76412966+0.14575444j]])

In [37]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [38]:
v.dot(w)

219

In [39]:
np.dot(v, w)

219

In [40]:
x.dot(v) # inner-product 

array([29, 67])

In [41]:
np.dot(x, v)

array([29, 67])

In [43]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [45]:
x @ y # 기호로도 사용하기 ㄴ한다. 

array([[19, 22],
       [43, 50]])

In [51]:
x = np.array([[1, 2], [3, 4]])
v = np.array([1, 2, 3])
x

array([[1, 2],
       [3, 4]])

In [57]:
v

array([1, 2, 3])

In [47]:
np.sum(x) # sum of all

10

In [48]:
np.sum(x, axis = 0) # sum of columns

array([4, 6])

In [50]:
np.sum(x , axis = 1) #sum of rows

array([3, 7])

In [52]:
np.sum(x , axis = -1) # row

array([3, 7])

In [53]:
np.sum(x, axis = -2) # col

array([4, 6])

In [54]:
np.sum(x, -1) # row

array([3, 7])

In [60]:
x.T # transpose

array([[1, 3],
       [2, 4]])

In [58]:
v.T # do nothing if one-dim

(3,)

In [61]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9], 
    [10, 11, 12]
    ])

v = np.array([1, 0, 1])

y = np.empty_like(x) # empty matrix, same shape with x
vv = np.tile(v, (4, 1)) # 4 rows of v 

In [69]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [68]:
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [67]:
z = x + vv
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [66]:
for i in range(4):
    y[i,:] = x[i, :] + v
print(y) # add v to each row of x

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [71]:
print(x + v) # broadcast 알아서 늘려갖고 연산을 수행한다.

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [72]:
broadcast = v.reshape(3, 1) + v
print(broadcast)

[[2 1 2]
 [1 0 1]
 [2 1 2]]


In [77]:
print(v.reshape(3, 1))
print(v)

[[1]
 [0]
 [1]]
[1 0 1]


In [78]:
v = np.array([1, 2, 3])
w = np.array([4, 5])
z = np.reshape(v, (3, 1)) * w # v array를 3 by 1 matrix로 reshape한다는 뜻.
print(z) # outer-product

[[ 4  5]
 [ 8 10]
 [12 15]]


In [88]:
x = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [89]:
x * 2 # element-wise multiplication 

array([[ 2,  4,  6],
       [ 8, 10, 12]])