In [1]:
import numpy as np 

In [2]:
np.isnan([np.log(-1.), 1., np.log(0)]) # NOT a Number

<ipython-input-2-e057152259aa>:1: RuntimeWarning: invalid value encountered in log
  np.isnan([np.log(-1.), 1., np.log(0)])
<ipython-input-2-e057152259aa>:1: RuntimeWarning: divide by zero encountered in log
  np.isnan([np.log(-1.), 1., np.log(0)])


array([ True, False, False])

In [3]:
np.isinf([np.log(-1.), 1., np.log(0)]) # infinity

<ipython-input-3-b1374075d08e>:1: RuntimeWarning: invalid value encountered in log
  np.isinf([np.log(-1.), 1., np.log(0)])
<ipython-input-3-b1374075d08e>:1: RuntimeWarning: divide by zero encountered in log
  np.isinf([np.log(-1.), 1., np.log(0)])


array([False, False,  True])

In [8]:
# nan 끼리는 비교연산이 불가하다. 
print(0 * np.nan)
print()
print(0 * np.nan == np.nan)


nan

False


In [11]:
np.inf > np.nan # 불가하다

False

In [12]:
np.nan - np.nan # nan을 빼도 nan이다

nan

In [13]:
0.3 == 3* 0.1 # 0.3 = 0.299999999999888~~~~

False

In [14]:
np.array(0) / np.array(0) # 0으로 나누는건 정의되지 않는다. 

<ipython-input-14-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [15]:
np.array(0) // np.array(0) # 몫은 0 

<ipython-input-15-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [16]:
np.zeros((31, 32))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [17]:
np.zeros((31, 33)) # element의 수가 1000개가 넘어가면 축약해서 보여준다. 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

In [19]:
np.set_printoptions( threshold = np.inf) # element가 1000개가 넘어가면 제한이던 것을 inf로 바꿔줌. 

In [20]:
np.zeros((50, 50))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [22]:
# from numpy import * 를 하게되면 np.array() 이런식으로 입력을 하지 않아도 array() 로 사용이 가능하다
# 그래서 아래 같은 부분에서는 numpy내에서의 sum 을 사용하기 때문에 차이가 있다. 
print(sum(range(5), -1))
from numpy import * 
print(sum(range(5), -1)) 

9
10


In [3]:
np.sum([1, 2, 3, 4, 5], -1) # numpy에서 -1은 axis 를 의미하기 때문에 값이 다르다.

15

In [2]:
sum([1, 2, 3, 4, 5], -1) # 일반 내장된 함수에서 -1은 숫자로 인식해서 sum에서 -1이 된다. 

14

In [5]:
z = np.ones((10, 11))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
z = np.zeros((8,8))
z = np.pad(z, pad_width = 1, mode = 'constant', constant_values = 1)
z # 8 by 8 0 matrix를 만들고 1로 padding

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
x = np.arange(9.).reshape(3, 3)
print(x)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [12]:
np.where( x > 5) # index 값이 출력

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [30]:
x[np.where( x > 3.0)]

array([4., 5., 6., 7., 8.])

In [31]:
np.where( x < 5, x, -1) # 5보다 작으면 그대로 x를 출력하고 5보다 크면 -1로 바꾸어 입력 

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])

In [32]:
np.where([
    [[True, False],
    [True, True]],
    [[1, 2],
    [3, 4]],
    [[5, 6],
    [7, 8]]    
])

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1], dtype=int64),
 array([0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [33]:
n = [
    [1, 2, 3],
    [4, 5, 6],
    [6, 7, 8]
    ]

det = np.linalg.det(n) # 행렬식 
print(det) # 0 에 근사하다. linearly dependent

-4.440892098500635e-15


- list vs array

In [35]:
[0, 1, 10] > [0, 2, 100] # list로 되어 있으면 전체를 비교한다. 

False

In [36]:
(0, 1, 10) > (0, 2, 100) # tuple도 역시 전체를 비교한다. 

False

In [37]:
[0, 1, 10] == [0, 2, 100] 

False

In [38]:
np.array([0, 1, 10]) > np.array([0, 2, 100]) # 개별로 비교한다다

array([False, False, False])

In [41]:
np.array((0, 1, 10)) > np.array((0, 2, 100))

array([False, False, False])

In [42]:
np.array([0, 1, 10]) == np.array([0, 2, 100])

array([ True, False, False])

In [44]:
a = np.array([[[1],[2],[3]]])
print('a', a, a.shape, sep= '\n')

a
[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [49]:
b = np.squeeze(a) # 모든 1차원 짜리가 사라진다. 
print(b.shape, b, sep = '\n')

(3,)
[1 2 3]


In [50]:
c = np.squeeze(a, axis = 0 ) # 0번째 차원의 길이가 1일 경우 사라진다.
c

array([[1],
       [2],
       [3]])

In [51]:
d = np.squeeze(a, axis = 2) # 2 번째 차원의 길이가 1일 경우 사라진다. 
# e = np.squeeze(a, axis = 1) 1번째 차원의 길이는 0이 아니기 때문에 에러가 출력. 
d

array([[1, 2, 3]])

In [52]:
f = np.array([1, 2, 3])
g = np.expand_dims(f, axis = 0) # 여기서 axis는 방향이 아니라 차원을 추가할 위치. 차원을 1이라고 표시
f.shape, g.shape

((3,), (1, 3))

In [55]:
h = np.expand_dims(f, axis = [1, 2]) 
f.shape, h.shape

((3,), (3, 1, 1))

In [61]:
# 프로그래밍 연습

a = [0, 1]*4
b = [1, 0]*4

In [81]:
a, b = [0, 1]*4, [1,0]*4 ;print(np.array([a,b]*4))


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [88]:
n = 8
arr = np.array([[(i+j) % 2 for i in range(n)] for j in range(n)]).reshape(n,n)
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])