In [1]:
import numpy as np 

In [14]:
# 21.Create a checkerboard 8x8 matrix using the tile function.

# 1
print(np.tile([0,1]*4 + [1,0]*4, 4).reshape((8,8)))

print()
# 2
print(np.tile( np.array([[0,1],[1,0]]), (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
# 22.Normalize a 5x5 random matrix 
# 1
print(np.random.normal( size = (5, 5)) )

print()
# 2 
Z = np.random.random((5, 5))
result = (Z - np.mean(Z)) / (np.std(Z))
print( result )

[[-0.79462942  0.5986757   1.19436649  1.16458378 -0.09469886]
 [ 0.1843041  -0.06187181  0.02499756  1.09528011 -2.03784795]
 [-1.32874518 -0.46189788  1.52575559 -0.13962421  0.76224024]
 [-0.06823425  0.35173493 -0.63027133 -0.57792982  0.59516559]
 [ 0.44856921 -0.98746939 -0.4407096   0.53111209 -0.14467817]]
[[-0.19944028  1.38946849  0.50755712 -0.51634786 -0.80628475]
 [ 0.12842329  1.61790591  1.00755709  0.41463371 -0.45140773]
 [ 0.92030712  0.21785392 -0.74738924 -1.17257851  0.92674885]
 [-1.33109054  0.90164258 -1.34097852  1.52313757 -0.09067032]
 [-1.28930388  1.47921919 -1.26763623 -1.30841822 -0.51290877]]


In [22]:
# 23.Create a custom dtype that describe a color as four unsigned bytes (RGBA)

color = np.dtype(
    [('r', np.ubyte),
     ('g', np.ubyte),
     ('b', np.ubyte),
     ('a', np.ubyte)])

color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [28]:
# 24.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
A, B = np.ones((5, 3)), np.ones((3, 2))

# 1
A.dot(B)

# 2
np.dot(A, B)

# 3
A @ B

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])