In [2]:
# 1.Import the numpy package under the name np
import numpy as np

In [3]:
# 2.Print the numpy version and the configuration 
print(np.__version__)
print(np.show_config) # configuration setting 

1.19.5
<function show at 0x000002A868225A60>


In [5]:
# 3.Create a null vector of size 100 
null_vector = np.zeros(100)
null_vector 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 4.How to find the memory size of any array
print(null_vector.size) # smiliar 'shape' 

print(null_vector.itemsize)

100
8


In [10]:
# 5.How to get the documentation of the numpy add function from the command line ?
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000002A86804E670>, toplevel='numpy')>

In [20]:
# 6.Create a null vector of size 10 but the fifth value which is 1 
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
# 7.Create a vector with values ranging from 10 to 49 
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [29]:
# 8.Reverse a vector (first element becomes last)
a = np.arange(10)
a[::-1]


[9 8 7 6 5 4 3 2 1 0]


In [28]:
# 9.Create 3x3 matrix with value ranging from 0 to 8
matrix = np.arange(9)
matrix.reshape(3, 3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
# 10.Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]
a = [1, 2, 0, 0, 4, 0]
np.nonzero(a) # [0, 1, 4] rocation indices 

(array([0, 1, 4], dtype=int64),)


In [51]:
# 11.Create a 3x3 identity matrix 

# 1
a = np.zeros((3, 3))
np.fill_diagonal(a, 1)
print(a)


# 2 
print(np.identity(3))

# 3 
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# 12.Create a 3x3x3 array with random values
np.random.random(27).reshape(3,3,3)

array([[[0.21576918, 0.22624033, 0.31270458],
        [0.02520791, 0.81488475, 0.86266001],
        [0.15233818, 0.33057435, 0.68731064]],

       [[0.53684341, 0.17322115, 0.48030894],
        [0.04864637, 0.70099546, 0.56979967],
        [0.46737916, 0.68867202, 0.68864581]],

       [[0.10627141, 0.92145683, 0.64292393],
        [0.62221087, 0.99485574, 0.70475001],
        [0.68362764, 0.38662506, 0.17370172]]])

In [50]:
# 13.Create a 10x10 array with random values and find the minimum and maximum values 
a = np.random.random(100).reshape(10,10)
print( np.max(a),', ' , np.min(a), sep = '')

0.9854160170862644, 0.001640059405348615


In [52]:
# 14.Create a random vector size 30 and find the mean values
a = np.random.random(30)
print(np.mean(a))

0.35156624335373565


In [84]:
# 15.Create a 2d array with 1 on the border and 0 inside
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0 
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
# 16.How to add a border (filled with 0's) around an existing array ?
np.pad([[0]], pad_width= 1,mode = 'constant', constant_values = 1)

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [8]:
# 17.What is the result of the following expression ? 
0 * np.nan # nan 

np.nan == np.nan # False

np.inf > np.nan # False 

np.nan - np.nan # nan 

np.nan in set([np.nan]) # True 

0.3 == 3* 0.1 # False 

False

In [18]:
# 18.Create a 5x5 matrix with values 1, 2, 3, 4 just below the digonal 
a = np.zeros((5, 5))
np.fill_diagonal(a, [1, 2, 3, 4, 5])
a 

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [26]:
# 19.Create a 8x8 matrix and fill it with a checkerboard pattern 
# 1
a = np.array([(i + j ) % 2 for i in range(8) for j in range(8) ]).reshape(8,8)
print(a)


# 2
a = np.array(([0,1] * 4 + [1, 0] * 4) * 4).reshape(8,8)
print(a)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [34]:
# 20.Consider a (6, 7, 8) shape array, what is the index (x, y, z) of the 100th element?
np.unravel_index(99, (6, 7, 8)) 

(1, 5, 3)